import Head from "next/head";
import Script from "next/script";
import React from "react";
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '@mui/material/styles';

import Feature from "components/category";
import { darkTheme } from "styles/theme";

export default function Home({ }) {
  return (
    <div>
      <Head>
        <title>MBTI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4530873656649886" crossOrigin="anonymous"></Script>

      <ThemeProvider theme={darkTheme}>
        <CssBaseline />
        <Feature />
      </ThemeProvider>
    </div>
  );
}
